// <auto-generated />
namespace K19_K32_Cap5_K19.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateLivro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateLivro));
        
        string IMigrationMetadata.Id
        {
            get { return "201604211314170_CreateLivro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
